### ISSUE TITLE
Extraneous spaces in A617.xml file

### ISSUE THREAD

**Issue by Matthew-Mullin** [Argonne-National-Laboratory/srlife#26]
file: https://github.com/Argonne-National-Laboratory/srlife/blob/master/srlife/data/damage/A617.xml

There are some extraneous spaces on lines 23 and 29 in the aforementioned file, which makes the file not readable to the destring_array function in srlife/materials.py for the temp ranges around 977.15 K and 1444.15 K

**Comment by reverendbedford** [comment]
Thanks for reporting this, it should be fixed now.
